MozillaIndia/mozillaindia.github.io

join/index.html

Now favicon will be visible. This will fix #58. :+1:

Fixed the favicon issue

---

index.html

Adding Firefox OS tab on homepage

---

index.html

Mozilla Punjab Channels added
Mozilla Gujarat instagram added

Regional Communities

---

index.html

removed all non-breakable spaces to fix the spacing between the links

fixed spacing issue on links

---

index.html

as suggested on issue #111 , groups and clubs have been sorted along with some spacing in club names

sorted alphabetically, fixed some spacing

---

index.html

fixed broken manifesto URL and added Mozilla Pune under regional group

fixed broken manifesto  URL & added regional group

---

index.html

contribute element expanded to match other elements of the page

contribute element expanded

---

CODE_OF_CONDUCT.md

Added code of conduct that points to Mozilla's participation guidelines

added code of conduct file 

---

index.html

- Added Mozilla Campus Club [GLUG MVIT](http://blog.glugmvit.com/) to the homepage.
- Added link to Mozilla Bangalore Meetup group.
More information about the club added to Issue #100

Add bangalore campus club and meetup links

---

index.html

added small info about campus clubs as suggested in issue #119

campus club info

---

index.html

added OpenDesign to Functional groups as suggested on issue #118

reference link to OpenDesign

---

index.html

removed extra telegram link in MozGuj section

removed extra link

---

index.html

Re-arranged Campus Club Nuv alphabetically

rearange cc Nuv

---

index.html

As per the discussion on issue #132 I've added the required attributes. There is more discussion needed to work on the color contrast

added attributes to make website more accessible

---

PULL_REQUEST_TEMPLATE.md
index.html

Fixed a small typo in the Social Media box

PR template and typo fix

---

.dockerignore
CONTRIBUTING.md
Dockerfile
docker-compose.yml

**Changes**: 
I have dockerized Mozilla India Website and it resulted in very lightweight **ngnix:alpine** based container. We can easily deploy to the cloud and even have the static site served instantly with a single command using docker-compose. I have made necessary documentation changes too. I believe it's a good option to developers.

Dockerized Mozilla India Website

---

index.html

Mozneurons changed to MozNeurons

MozNeurons updated

---

src/components/header.js

Fixes #153 
**Changes**: 
The header wasn't responsive earlier. The hamburger icon didn't show the menu. This is fixed in this PR.
**Screenshots for the change**:

Responsive header 153

---

CONTRIBUTING.md
LICENSE

Fixes #152  
**Changes**: 
The LICENSE is updated and the contribution guidelines have been added.
**Screenshots for the change**:

Updated License and added contribution guidelines

---

package.json
scripts/deploy-github.js

dev: deployment script

---

.github/PULL_REQUEST_TEMPLATE.md

**Changes**: 
Added before and after in PR template so that collaborators can view the changes side by side in the PR itself.
**Screenshots for the change**: 
No UI changes were made

before and after in PR template

---

src/pages/index.js

Pass appropriate size unit to font-awesome element and adjust envelope icon size to match with other icons. #165
Fixes #165
**Changes**: 
Ensured font awesome icon elements is getting valid size input and adjusted envelope icon size to align with other icons.
**Screenshots for the change**:

Pass appropriate size unit to font-awesome element. #165

---

data/functionalgroups.json
data/regionalgroups.json
src/components/groups.js
src/pages/index.js

Fixes #[161] 
**Changes**: 
Changed "GitHub" to "github" in data files

Changed GitHub to github in the data files

---

package-lock.json
src/components/groups.js
src/components/layout.css

Fixes #162 
**Changes**: 
Changed social media text for icons instead
**Screenshots for the change**: 
Before: 
After: ![issue 162](https://user-images.githubusercontent.com/42707467/67828180-78ce2d00-faa0-11e9-8859-ffe4c4d65269.jpg)

replaced social media text for icons

---

.eslintrc.js
data/campusclubs.json
data/functionalgroups.json
data/regionalgroups.json
package.json
src/components/group.js
src/components/groups.js
src/components/layout.css
src/components/social-link.js
src/pages/index.js
yarn.lock

Continuation of #203, closes #203
Fixes #173 (eslint rules setup based on react-app standard)
Fixes #160 (so does #203)
Gets rid of bulma's tile nesting hell by sticking to flexboxes.
Also makes some package.json corrections
**Screenshots for the change**: 
Before:
After:

Improvements
